---

- hosts: goodshepardhosts
  become: true
  tasks:

  - name: Clean up apt cache
    apt:      
      autoremove: yes
      autoclean: yes
      update_cache: yes
      force_apt_get: true
    when: ansible_distribution in ["ClearLinux", "Ubuntu", "Debian"]
