all:
  hosts: 
    goodshepardnetwork:
      hosts:   
        10.1.10.110
        10.1.10.106
        10.1.10.112
    ubuntu:  
      hosts:     
        10.1.10.110
        10.1.10.106
        10.1.10.112