---

- hosts: goodshepardhosts
  become: true
  tasks:

  - name: Update system repository index
    package:
      name: "*"
      update_cache: yes
      force_apt_get: true
      state: latest
    when: ansible_distribution in ["ClearLinux","Ubuntu"]
